baseURL: 127.0.0.1
title: 韩涛的个人简历
theme: hugo-resume

defaultContentLanguage: zh
hasCJKLanguage: true

googleAnalytics: "G-N7J9N4KYLS"

color: 

languages:
  zh:
    languageCode: zh
    languageName: 简体中文