name: My Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [Release site]
    types:
      - completed
    branches:
      - my_resume

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - run: env
